# Generated by Django 6.0.5 on 2026-06-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['customer_id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('ship_date', models.DateField()),
                ('ship_mode', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('sales', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField()),
                ('profit', models.FloatField()),
                ('profit_margin_pct', models.FloatField(blank=True, null=True)),
                ('delivery_days', models.IntegerField(blank=True, null=True)),
                ('revenue_per_unit', models.FloatField(blank=True, null=True)),
                ('clv_bucket', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='analytics.customer')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='RfmSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('monetary', models.FloatField()),
                ('r_score', models.IntegerField()),
                ('f_score', models.IntegerField()),
                ('m_score', models.IntegerField()),
                ('rfm_score', models.IntegerField()),
                ('segment', models.CharField(max_length=50)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfm', to='analytics.customer')),
            ],
            options={
                'ordering': ['-monetary'],
            },
        ),
    ]
